#ifndef CONFIG_HPP
#define CONFIG_HPP

#define ADMIN_ONLY_REGISTRATION true
#define ADMINS_CAN_SEND_QUERIES true
#define USERS_CAN_CHANGE_CHANNELS true
#define USERS_CAN_CREATE_CHANNELS true
#define CLIENT_MESSAGES_ARE_DEBUGGED true
#define PING_PONG_DELAY 5000

#endif // CONFIG_HPP
